var labels={
lblLearnEnglish:"英语教学",
lblLearnMandarian:"国语教学",
lblLearnCantanes:"广东语教学",
lblLearnSpanish:"西班牙语教学",
lblLearnJapanese:"日语教学",
lblTeacherSignIn:"Teacher Sign In",
lblTeacherSignup:"Teacher Sign Up",
lblSearch : "搜寻导帅 / 地区",
lblShowAll :"国",
lblYoutubeVideos:"国",
lblHome :"国语教学",
lblName :"导帅名称",
lblLocation :"国家",
lblName1:"导帅名称",
lblUniversity:"就读大学",
lblYearOfExp:"教学经验",
lblEmail:"电邮",
lblPhone:"电话",
lblDescription:"个人简介",
lblMobileNo:"手机号码",
lblIntroVideo:"介绍视频",
lblSampleVideo:"教学视频",
lblLiveSessionTime:"每段课堂时间",
lblLiveSessionDate:"现场课堂日期",
lblLive:"国",
lblGoLive:"zhGo Live", 
lblUploadPhoto:"zhUpload Photo",
lblUploadVideo:"zhUpload Video",
lblPhoto:"名称",
lblVideo:"zhVideo",
lblUpload:"zhUpload",
lblCategory:"zhCategory",
lblSave:"zhSave Teacher Profile",
lblStudent:"zhStudent",
lblTeacher:"zhTeacher",
lblBack:"zhBack",
lblDismissSession:"zhDismiss Session",
lblApprove:"zhApprove",
lblLogout:"zhChange Langugage",
lbllogin:"zhLogin",
lblpasswd:"zhPassword",
lblMyScheduleManager:"zhMyScheduleManager",
lblWelcome:"zhWelcome ", 
lblApproveTeachers:"zhApprove Teachers"
}

