var labels ={
lblLearnEnglish:"Learn English",
lblLearnMandarian:"Learn Mandarian",
lblLearnCantanes:"Learn Cantanes",
lblLearnSpanish:"Learn Spanish",
lblLearnJapanese:"Learn Japanese",
lblTeacherSignIn:"Teacher Sign In",
lblTeacherSignup:"Teacher Sign Up",
lblSearch : "Search By Name / Location",
lblShowAll :"Show All >>",
lblShowDtl :"Verify Teacher ",
lblYoutubeVideos: "Youtube Videos",
lblHome :"Home",
lblName :"Name",
lblLocation :"Location",
lblName1:"Name",
lblUniversity:"University",
lblYearOfExp:"Years Of Experience",
lblEmail:"E-Mail",
lblPhone:"Phone No",
lblDescription:"Description",
lblMobileNo:"Mobile No",
lblIntroVideo:"Intro Video's",
lblSampleVideo:"Sample Videos",
lblLiveSessionTime:"Live Session Time",
lblLiveSessionDate:"Live Session Date",
lblLive:"Live", 
lblGoLive:"Go Live", 
lblUploadPhoto:"Upload Photo",
lblUploadVideo:"Upload Video",
lblUploadCerti:"Upload Certificate",
lblPhoto:"Photo",
lblVideo:"Video",
lblUpload:"Upload",
lblCertificate:"Certificate",
lblCategory:"Category",
lblSave:"Save Teacher Profile",
lblStudent:"Student",
lblTeacher:"Teacher",
lblBack:"Back",
lblDismissSession:"Cancel",
lblApprove:"Approve",
lblReject:"Reject",
lblLogout:"Change Language",
lbllogin:"Login",
lblpasswd:"Password",
lblMyScheduleManager:"My Schedule",
lblWelcome:"Welcome ", 
lblLanguage:"Language",
lblAdd:"Add",
lblForgotPassword:"Forgot Password",
lblApproveTeachers:"Teachers Pending for Approval"
 

}

