var labels ={
lblLearnEnglish:"jpLearn English",
lblLearnMandarian:"jpLearn Mandarian",
lblLearnCantanes:"jpLearn Cantanes",
lblLearnSpanish:"jpLearn Spanish",
lblLearnJapanese:"jpLearn Japan",
lblTeacherSignIn:"jpTeacher Sign In",
lblTeacherSignup:"jpTeacher Sign Up",
lblSearch :"jpSearch By Name / Location",
lblShowAll :"jpShow All >>",
lblYoutubeVideos:"jpYoutube Videos",
lblHome :"jpHome",
lblName :"jpName",
lblLocation :"jpLocation",
lblName1:"jpName",
lblUniversity:"jpUniversity",
lblYearOfExp:"jpYears Of <br>Experience",
lblEmail:"jpE-Mail",
lblPhone:"jpPhone No",
lblDescription:"jpDescription",
lblMobileNo:"jpMobile No",
lblIntroVideo:"jpIntro Video's",
lblSampleVideo:"jpSample Videos",
lblLiveSessionTime:"jpLive Session Time",
lblLiveSessionDate:"jpLive Session Date",
lblLive:"jpLive", 
lblGoLive:"jpGo Live", 
lblUploadPhoto:"jpUpload Photo",
lblUploadVideo:"jpUpload Video",
lblPhoto:"jpPhoto",
lblVideo:"jpVideo",
lblUpload:"jpUpload",
lblCategory:"jpCategory",
lblSave:"jpSave Teacher Profile",
lblStudent:"jpStudent",
lblTeacher:"jpTeacher",
lblBack:"jpBack",
lblDismissSession:"jpDismiss Session",
lblApprove:"jpApprove",
lblReject:"jpReject",
lblLogout:"jpChange Language",
lbllogin:"jpLogin",
lblpasswd:"jpPassword",
lblMyScheduleManager:"jpMyScheduleManager",
lblWelcome:"jpWelcome ", 
lblApproveTeachers:"jpTeachers Pending for Approval"
}

