var labels={
lblLearnEnglish:"英語教學",
lblLearnMandarian:"國語教學",
lblLearnCantanes:"廣東語教學",
lblLearnSpanish:"西班牙語教學",
lblLearnJapanese:"日語教學",
lblTeacherSignIn:"Teacher Sign In",
lblTeacherSignup:"Teacher Sign Up",
lblSearch : "搜尋導帥 / 地區",
lblShowAll :"學",
lblYoutubeVideos:"學",
lblHome :"學",
lblName :"導帥名稱",
lblLocation :"國家",
lblName1:"名稱",
lblUniversity:"就讀大學",
lblYearOfExp:"教學經驗",
lblEmail:"電郵",
lblPhone:"電話",
lblDescription:"個人簡介",
lblMobileNo:"手機號碼",
lblIntroVideo:"介紹視頻",
lblSampleVideo:"教學視頻",
lblLiveSessionTime:"每段課堂時間",
lblLiveSessionDate:"現場課堂日期",
lblLive:"學",
lblGoLive:"chGo Live",  
lblUploadPhoto:"chUpload Photo",
lblUploadVideo:"chUpload Video",
lblPhoto:"名稱",
lblVideo:"chVideo",
lblUpload:"chUpload",
lblCategory:"chCategory",
lblSave:"chSave Teacher Profile",
lblStudent:"chStudent",
lblTeacher:"chTeacher",
lblBack:"chBack",
lblDismissSession:"chDismiss Session",
lblApprove:"chApprove",
lblReject:"chReject",
lblLogout:"chChange Language",
lbllogin:"chLogin",
lblpasswd:"chPassword",
lblMyScheduleManager:"chMyScheduleManager",
lblWelcome:"chWelcome ", 
lblApproveTeachers:"chTeachers Pending for Approval"
}
