var labels ={
lblLearnEnglish:"Learn English",
lblLearnMandarian:"Learn Mandarian",
lblLearnCantanes:"Learn Cantanes",
lblLearnSpanish:"Learn Spanish",
lblLearnJapanese:"Learn Japanese",
lblTeacherSignIn:"Teacher Sign In",
lblTeacherSignup:"Teacher Sign Up",
lblSearch : "Search By Name / Location",
lblShowAll :"Show All >>",
lblYoutubeVideos: "Youtube Videos",
lblHome :"Home",
lblName :"Name",
lblLocation :"Location",
lblName1:"Name",
lblUniversity:"University",
lblYearOfExp:"Years Of <br>Experience",
lblEmail:"E-Mail",
lblPhone:"Phone No",
lblDescription:"Description",
lblMobileNo:"Mobile No",
lblIntroVideo:"Intro Video's",
lblSampleVideo:"Sample Videos",
lblLiveSessionTime:"Live Session Time",
lblLiveSessionDate:"Live Session Date",
lblLive:"Live", 
lblGoLive:"Go Live", 
lblUploadPhoto:"Upload Photo",
lblUploadVideo:"Upload Video",
lblPhoto:"Photo",
lblVideo:"Video",
lblUpload:"Upload",
lblCategory:"Category",
lblSave:"Save Teacher Profile",
lblStudent:"Student",
lblTeacher:"Teacher",
lblBack:"Back",
lblDismissSession:"Dismiss Session",
lblApprove:"Approve",
lblLogout:"Change Language",
lbllogin:"Login",
lblpasswd:"Password",
lblMyScheduleManager:"My Schedule",
lblWelcome:"Welcome ", 
lblApproveTeachers:"Approve Teachers"
 

}

